### ISSUE TITLE
Async/Future based .run()

### ISSUE THREAD

**Issue by theduke** [neo4j/neo4j-java-driver#102]
I know this is still a WIP,

but are you planning on adding an async version of .run() which returns a Future?

**Comment by jakewins** [comment]
Yes - although we've discussed adding a Reactive Streams based API, rather than using a future, so it'd be similar to how the javascript driver handles async results. You could build a Future-based API on top of that easily tho.

The underlying protocol, Bolt, is asynchronous, so this is just a matter of exposing that in this driver.

Out of curiosity - what's your use case?

**Comment by theduke** [comment]
I'm using Neo4j with Akka (http://akka.io/), where you are supposed to block as little as possible.

**Comment by JacobASeverson** [comment]
+1 :-)

**Comment by lpfeup** [comment]
I would also be interested in this. Also using Neo4j with Akka.

**Comment by jn73** [comment]
Any update on this? I'm working on a akka http service and this would help a lot.

**Comment by PhilAndrew** [comment]
+1 async is really a requirement for performance.  holding onto many threads with one thread per request to the database is analogous to why we now use non blocking web server's.  

For people in the Scala world we really never ever do blocking IO, its considered a horrible sin, so its difficult to use this within the Scala world. Java people also try not to do blocking IO.

**Comment by jellybams** [comment]
+1 for use with akka-http + akka-streams

**Comment by dazraf** [comment]
This would be an invaluable API. With toolkits like Akka, Vert.x and others, we are finding that we can get significantly greater performance with asynchronous APIs. _Please Note:_ the API should not be Future based because, like most database APIs, the key is asynchronous processing of result _streams_ not result _sets_. Please consider implementing this API using something like RxJava Observables; or equivalent. Thanks.

**Comment by PhilAndrew** [comment]
Agree Akka Streams would be good as it works well in Java and Scala world.

**Comment by technige** [comment]
This is now on our roadmap.

**Comment by vicaba** [comment]
@technige where can i track the async api development?

**Comment by lutovich** [comment]
Hello everyone!

We've made some progress on the async API and here is an initial PR: https://github.com/neo4j/neo4j-java-driver/pull/402.
Reviews, opinions and feedback are extremely welcome!

It will take us a bit more to release draft of async API in an alpha release. You are, of course, very welcome to build and try it out before that :)

**Comment by lutovich** [comment]
Hello again,

We've released first alpha version of the driver with async API. It is now available in Maven Central: https://search.maven.org/#artifactdetails%7Corg.neo4j.driver%7Cneo4j-java-driver%7C1.5.0-alpha02%7Cjar.

**Everyones** feedback is extremely welcome! Please try it out and post your thoughts in this thread!
**Note:** this version is not production ready, it is more like a taster of the async API.

**Comment by lutovich** [comment]
Hi,

We've released 1.5.0 version of the driver with async API. Feedback is very welcome!
I'll close this issue, thanks a lot for the input.

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Flow Control, Back Pressure & Reactive Drivers](https://trello.com/c/Q74jCr78/132-flow-control-back-pressure-reactive-drivers)
