### ISSUE TITLE
Routing servers are not updated in time when opening a new session with a different database.

### ISSUE THREAD

**Issue by michael-simons** [neo4j/neo4j-java-driver#1207]
This comes in via @ikwattro 

In a scenario in which an existing driver connection is used to create a database in a cluster and the same connection than is used with a different session, the routing table gets updated too late and there's no way to trigger an update manually, apart from sleeping. In environments with managed drivers (Quarkus, Boot etc.), it is not an option to close and reopen the driver.

Here's a reproducer

```java
package a;

import java.net.URI;

import org.junit.jupiter.api.Test;
import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.GraphDatabase;
import org.neo4j.driver.SessionConfig;
import org.neo4j.junit.jupiter.causal_cluster.CausalCluster;
import org.neo4j.junit.jupiter.causal_cluster.NeedsCausalCluster;

@NeedsCausalCluster(password = ClusterDBTest.PASSWORD) // (1)
public class ClusterDBTest {

	static final String USERNAME = "neo4j";
	static final String PASSWORD = "cc";

	@CausalCluster // (2)
	private static URI neo4jUri;

	@Test
	void aTest() throws InterruptedException {

		try (var driver = GraphDatabase.driver(neo4jUri, AuthTokens.basic(USERNAME, PASSWORD))) {
			driver.verifyConnectivity();
			try (var session = driver.session(SessionConfig.forDatabase("system"))) {
				session.run("DROP DATABASE foo IF EXISTS").consume();
				session.run("CREATE DATABASE foo IF NOT EXISTS").consume();
			}

			// Thread.sleep(5_000); // Doing some sleep is enough to make things work
			
			try (var session = driver.session(SessionConfig.forDatabase("foo"))) {
				session.run("MATCH (n) RETURN count(n)").consume();
			}
		}
	}
}
```

and the necessary dependencies

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.example</groupId>
	<artifactId>cluster</artifactId>
	<version>1.0-SNAPSHOT</version>

	<properties>
		<maven.compiler.release>11</maven.compiler.release>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.neo4j.driver</groupId>
			<artifactId>neo4j-java-driver</artifactId>
			<version>4.4.5</version>
		</dependency>
		<dependency>
			<groupId>eu.michael-simons.neo4j</groupId>
			<artifactId>junit-jupiter-causal-cluster-testcontainer-extension</artifactId>
			<version>2022.0.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>5.8.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.36</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
			</plugin>
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.2</version>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.22.2</version>
			</plugin>
		</plugins>
	</build>
</project>
```

**Comment by injectives** [comment]
Thanks for the report and reproduction steps 👍 

I enabled logging and checked what happens over the wire. During my testing the last query actually used a different connection. It failed because server replied with `FAILURE Neo.TransientError.Database.DatabaseUnavailable "Cannot route requests for database foo"` when driver tried fetching routing table for database `foo`.

As far as I am aware, `CREATE DATABASE foo IF NOT EXISTS` is actually async and does not guarantee that database is created by the time the command completes. Here is a blocking variant: `CREATE DATABASE foo IF NOT EXISTS WAIT`.

However, even with blocking variant the suggested code fails because the last query needs a `WRITE` connection and the new database does not have a writer immediately and returns routing table with readers only.

To make it work, I had to update the latter part to: `session.writeTransaction( tx -> tx.run( "MATCH (n) RETURN count(n)" ).consume() )`.

**Comment by injectives** [comment]
Thanks for the report and reproduction steps 👍 

I enabled logging and checked what happens over the wire. In my testing the last query actually used a different connection.

It fails because server replies with `FAILURE Neo.TransientError.Database.DatabaseUnavailable "Cannot route requests for database foo"` when driver tries fetching routing table for database `foo`.

As far as I am aware, `CREATE DATABASE foo IF NOT EXISTS` is actually async and does not guarantee that database is created by the time the command completes. Here is a waiting variant: `CREATE DATABASE foo IF NOT EXISTS WAIT`.

However, even with waiting option the code may fail because the database might not have a writer that is needed for the last query.

One way of making this work is to make sure that the last query is retried when there are no writers. Example: `session.writeTransaction( tx -> tx.run( "MATCH (n) RETURN count(n)" ).consume() )`.

**Comment by injectives** [comment]
@michael-simons, just wanted to check if the above makes sense and whether there is anything outstanding on this issue?

**Comment by injectives** [comment]
Please reopen if there are points that have been missed on the driver side.
