### ISSUE TITLE
spring-boot-starter-data-neo4j(3.0.6)-> spring-data-neo4j(7.0.5)-> neo4j-java-driver(5.7.0) ->Cannot invoke "org.neo4j.driver.summary.InputPosition.line()" because "position" is null

### ISSUE THREAD

**Issue by SHIVANGIJOSHI** [neo4j/neo4j-java-driver#1549]
- Neo4j version: 5.19-aura
- Neo4j Mode: neo4j aura DB professional
- Driver version: Java language driver 5.7.0
- Operating system: Ubuntu 20.04
- **Steps to reproduce**
Executed this query using a custom repository
`OPTIONAL MATCH shortestPath((pr:Role:`DQ`{status:"ACTIVE",category:"ADMIN",type:$userRole})-[:MANAGES*..3]->(r:Role:`DQ`{status:"ACTIVE"}))
WHERE r.type <> $userRole AND NOT r.type IN $excludedRoles
WITH collect(r) as adminRoles
OPTIONAL MATCH (ur:Role:`DQ`{status:"ACTIVE",category:"USER"})
WHERE ur.type <> $userRole AND NOT ur.type IN $excludedRoles
WITH adminRoles,collect(ur) as userRoles
WITH adminRoles+userRoles as roles
UNWIND roles as role
RETURN role{.code,.type}
SKIP $offset
LIMIT $limit`

```
public interface RoleRepo extends Neo4jRepository<Role, String> 
@Query("OPTIONAL MATCH shortestPath((pr:Role:`:#{literal(#module)}`{status:\"ACTIVE\",category:\"ADMIN\",type:$userRole})-[:MANAGES*..11]->(r:Role:`DQ`{status:\"ACTIVE\"}))\n"
                        + //
                        "WHERE r.type <> $userRole AND NOT r.type IN $excludedRoles\n" + //
                        "WITH collect(r) as adminRoles\n" + //
                        "OPTIONAL MATCH (ur:Role:`:#{literal(#module)}`{status:\"ACTIVE\",category:\"USER\"})\n"
                        + //
                        "WHERE ur.type <> $userRole AND NOT ur.type IN $excludedRoles\n" + //
                        "WITH adminRoles,collect(ur) as userRoles\n" + //
                        "WITH adminRoles+userRoles as roles\n" + //
                        "UNWIND roles as r\n" + //
                        "RETURN r{.code,.type}\n" + //
                        "SKIP $offset\n" + //
                        "LIMIT $limit")
        List<RoleProjection> fetchAllhierarchicallyMappable(@Param("userRole") String userRole,
                        @Param("module") String module,
                        @Param("excludedRoles") Set<String> excludedRoles,
                        @Param("offset") int offset, @Param("limit") int pageSize);
```
Expected behavior
List of RoleProjection object
Note:- working fine with
Neo4j Community "5.11.0"
Actual behavior
`Cannot invoke "org.neo4j.driver.summary.InputPosition.line()" because "position" is null`

**Comment by michael-simons** [comment]
Please upgrade your SDN version. This is not a bug in the driver:

The following versions contain the required bug fix. 
All patch versions for both SDN and Neo4j-OGM are drop-in replacements and don't require code changes.

SDN:
Relevant PR / Issue: https://github.com/spring-projects/spring-data-neo4j/pull/2822

* Since 7.0.12 (Included in Spring Boot 3.0.13)
* Since 7.1.6 (Included in Spring Boot 3.1.6)
* Since 7.2.0 (Included in Spring Boot 3.2.0)
* All of 7.3.x and higher (3.3.0)

SDN 6.x is out of support and requires commercial support from Broadcom.

Relevant PR / Issue: https://github.com/neo4j/neo4j-ogm/issues/950

Neo4j-OGM:
* 3.2.41 and higher
* 3.3.0 and higher
* 4.0.6 and higher

Thank you and sorry for the inconvenience.
