### ISSUE TITLE
Make driver fail fast algorithm configurable

### ISSUE THREAD

**Issue by snicoll** [neo4j/neo4j-java-driver#380]
[This commit](https://github.com/neo4j/neo4j-java-driver/commit/a81b2389b96b2af5ebe6629d0209ff9f672e4352) has the side effect that any attempt to create a `SessionFactory` requires a Neo4J server running. 

This is a problem in Spring Boot (specifically for the integration tests) as we don't need to actually access to Neo4j but would like to validate other pieces of the configuration. I also think this can be surprising for users when they upgrade. 

Can you make this behaviour configurable somehow?

**Comment by lutovich** [comment]
Hi @snicoll,

Thanks for reporting this problem.

Mentioned commit was mainly triggered by problems in neo4j-jdbc testing which had troubles because of driver's lazy connectivity. It was also meant to align behaviour of direct (`bolt` scheme) and routing (`bolt+routing` scheme) drivers. Later one has always been eager wrt connectivity because it tries to fetch cluster configuration on creation.

Fail-fast behaviour behaviour **seems** like a safe default. It prevents client applications from executing business logic while driver instance is not functional (wrong credentials or database unavailable). Does it makes sense to you?

Could you please share more details about your testing infra? What pieces of configuration need to be validated? Links to code would be appreciated.

We could potentially introduce a config option. This however would be a surface change and it'll only appear in the Java driver.

**Comment by snicoll** [comment]
@lutovich thanks for the fast reply.

That change, with no ability to disable it, caught us by surprise and I suspect others might as well. It isn't specifically about what makes sense to do for an _application_. This is about when you're testing components and Neo4j is involved.

There are a bunch of tests that validates the internal configuration of the `SessionFactory` for instance. We do not need to connect to any server at that point (we're validating the local config of the client if you will). For things were we need to connect to a server, we use [Neo4jTestServer](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-test-autoconfigure/src/test/java/org/springframework/boot/test/autoconfigure/data/neo4j/Neo4jTestServer.java) but since the context is failing on startup now, it is close to useless.

Why don't you make this an opt-in thing? We have the exact opposite use case with users willing the app to start even if the underlying store is not available yet.

**Comment by frant-hartm** [comment]
A `verifyConnection` configuration option has been added to OGM with default value `false`, which causes the neo4j java driver instance to be created lazily.

https://github.com/neo4j/neo4j-ogm/blob/master/api/src/main/java/org/neo4j/ogm/config/Configuration.java#L337

I still think this should be done in the driver directly. Most applications using driver directly will need to implement this themselves.

@lutovich
> It prevents client applications from executing business logic while driver instance is not functional

but clients won't (should not?) execute BL before they start a transaction, it would be fine, expected actually, to throw `ServiceUnavailableException` from `driver.session`

**Comment by snicoll** [comment]
@frant-hartm Thanks, I can confirm this is fixing the issue on our side.
