### ISSUE TITLE
Take raw JSON

### ISSUE THREAD

**Issue by RaulGF92** [neo4j/neo4j-java-driver#509]
Hi i'm taking queries using java driver and need take the raw statementResult, how i can get that? Thanks you. I will put a piece code like example.

```
Driver driver = GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("neo4j", "PasSW0rd"));
try (Session session = driver.session()) {
    StatementResult rs = session.run("MATCH (n) RETURN n");
    // Take here a json raw
}
driver.close();
```

I expect something like this:

``` (json)
[
  {
    "keys": [
      "n"
    ],
    "length": 1,
    "_fields": [
      {
        "identity": {
          "low": 23,
          "high": 0
        },
        "labels": [
          "Node"
        ],
        "properties": {
          "name": "EG - DIRECCION DE CENTRAL COMPRAS BAZAR",
          "identificator": "MODU426"
        }
      }
    ],
    "_fieldLookup": {
      "n": 0
    }
  },
  {
    "keys": [
      "n"
    ],
    "length": 1,
    "_fields": [
      {
        "identity": {
          "low": 24,
          "high": 0
        },
        "labels": [
          "Node"
        ],
        "properties": {
          "name": "CIRCUITOS RCM",
          "identificator": "APLI238"
        }
      }
    ],
    "_fieldLookup": {
      "n": 0
    }
  }
]
```

**Comment by zhenlineo** [comment]
Hi, this driver is running on binary protocol Bolt. There is no Json ever used in the transmission. If you want to get the result in json, then you need to define how the convention looks like from each driver Value to json. And write your own static valueToJsonString method.

The js driver has some json format but that’s because it is JavaScript :)
For java driver, you have the cypher value objects, you can convert to json string, cypher string, an Person object or whatever you like.

Cheers,
Zhen

**Comment by RaulGF92** [comment]
Thanks man!! I keep trying other solution
