### ISSUE TITLE
Connecting to a database using SSL client authentication

### ISSUE THREAD

**Issue by philippbussche** [neo4j/neo4j-java-driver#513]
Hi,
I want to run my graph database behind an Nginx proxy which is enforcing SSL client certificates.
In my Java client application how would I provide a client certificate when building the driver object ?
Thanks
Philipp

**Comment by lutovich** [comment]
Hi @philippbussche,

Currently, drivers do not support client certificate authentication. We have discussed this feature but have no concrete plan for it at the moment.

**Comment by philippbussche** [comment]
Thanks @lutovich . What would you recommend in term of securing a neo4j instance that needs to be accessible on the Internet ? Would bolt+Basic Auth be secure (enough) ?
Thank you for your help
Philipp

**Comment by lutovich** [comment]
I think it is worth making driver only connect to a database that presents a specific signed certificate. It can be configured using [this method](https://neo4j.com/docs/api/java-driver/current/org/neo4j/driver/v1/Config.TrustStrategy.html#trustCustomCertificateSignedBy-java.io.File-). Also starting from 1.7 it will be possible to enable host name verification on the client using `TrustStrategy#withHostnameVerification()` method. These two things should prevent the driver from connecting to a spoofed database.

Encryption should always be turned on as well (it is turned on by default). Credentials can supplied as a username & password pair. Driver also supports Kerberos authentication and can accept a token via `AuthTokens#kerberos(String)` [method](https://neo4j.com/docs/api/java-driver/current/org/neo4j/driver/v1/AuthTokens.html#kerberos-java.lang.String-).

**Comment by ghost** [comment]
Hallo
I have a problem with connecting neo4j server with java.
I wrote the following code

import org.neo4j.driver.v1.AuthTokens;
import org.neo4j.driver.v1.Driver;
import org.neo4j.driver.v1.GraphDatabase;
import org.neo4j.driver.v1.Session;
import org.neo4j.driver.v1.StatementResult;
import org.neo4j.driver.v1.Transaction;
import org.neo4j.driver.v1.TransactionWork;


import static org.neo4j.driver.v1.Values.parameters;



public class D implements AutoCloseable{

     private final D driver;

    public D( String uri, String user, String password )
    {
       driver =  (D) GraphDatabase.driver( uri, AuthTokens.basic( user, password ) );
    }

    @Override
    public void close() throws Exception
    {
        driver.close();
    }
    public void CreateNode( )
    {
        try ( Session session = driver.session())
        {
           StatementResult rs = session.run("CREATE (n:name{'issa'}) RETURN n");
        }
    }
    public static void main(String[] args) throws Exception {
        try ( D d = new D( "bolt://localhost:7687", "neo4j", "hanna125" ) )
        {
            d.CreateNode();
        }
    }

but during rumtime I have got the following error

cd C:\Users\Hanna Abboud\Documents\NetBeansProjects\Neo; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_181" cmd /c "\"\"C:\\Program Files\\NetBeans 8.2\\java\\maven\\bin\\mvn.bat\" -Dexec.args=\"-classpath %classpath com.mycompany.neo.Driver\" -Dexec.executable=\"C:\\Program Files\\Java\\jdk1.8.0_181\\bin\\java.exe\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.2\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building Neo 1.0-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ Neo ---
Sep 01, 2018 9:05:21 AM org.neo4j.driver.internal.logging.JULogger info
INFO: Direct driver instance 327177752 created for server address localhost:7687
Exception in thread "main" java.lang.ClassCastException: org.neo4j.driver.internal.InternalDriver cannot be cast to com.mycompany.neo.Driver
	at com.mycompany.neo.Driver.<init>(Driver.java:28)
	at com.mycompany.neo.Driver.main(Driver.java:47)

If there is any idea please help me 
thnks

**Comment by lutovich** [comment]
Hi @hannaabboud,

I think your problem is not related to the one reported in this issue.

You do not need to cast driver to `D`, the return type of `GraphDatabase#driver()` is `org.neo4j.driver.v1.Driver`. This code should work:

```java
import org.neo4j.driver.v1.AuthTokens;
import org.neo4j.driver.v1.Driver;
import org.neo4j.driver.v1.GraphDatabase;
import org.neo4j.driver.v1.Session;
import org.neo4j.driver.v1.StatementResult;
import org.neo4j.driver.v1.Transaction;
import org.neo4j.driver.v1.TransactionWork;

import static org.neo4j.driver.v1.Values.parameters;

public class D implements AutoCloseable{

 private final D driver;

public D( String uri, String user, String password )
{
   driver =  GraphDatabase.driver( uri, AuthTokens.basic( user, password ) );
}

@Override
public void close() throws Exception
{
    driver.close();
}
public void CreateNode( )
{
    try ( Session session = driver.session())
    {
       StatementResult rs = session.run("CREATE (n:name{'issa'}) RETURN n");
    }
}
public static void main(String[] args) throws Exception {
    try ( D d = new D( "bolt://localhost:7687", "neo4j", "hanna125" ) )
    {
        d.CreateNode();
    }
}
```

Hope this helps.

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Client-authenticated TLS connection](https://trello.com/c/7VQ67xIs/380-client-authenticated-tls-connection)

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Client certificate support for TLS](https://trello.com/c/F7bzlSM6/266-client-certificate-support-for-tls)

**Comment by zhenlineo** [comment]
Hi @philippbussche,

We will take you feature request into our future work for drivers. It looks to me that you've solved the driver connection issue with the database. Therefore I am closing this issue now.

Regards,
Zhen
