### ISSUE TITLE
Misleading exception and error message when null passed as a query

### ISSUE THREAD

**Issue by nmervaillie** [neo4j/neo4j-java-driver#535]
Using driver 1.6.2, using null as a query parameter throws 
`org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database`

Expected behavior: get a `ClientException`

```
@ClassRule
public static Neo4jRule neo4j = new Neo4jRule();

@Test(expected = ClientException.class)
public void should_throw_client_exception_if_statement_null() {

    Driver driver = GraphDatabase.driver(neo4j.boltURI(), AuthTokens.basic("", ""), Config.build().withoutEncryption().toConfig());

    try (Session session = driver.session()) {
        session.run((String)null).consume();
    }
}
```

**Comment by zhenlineo** [comment]
Hi @nmervaillie 

Thanks for reporting this bug to us. We have fixed since `1.7.0-beta02` ([Commit](https://github.com/neo4j/neo4j-java-driver/commit/fb4a453a6e683a4a9f5b4c9942d13e809b2acb35))

Once it is fully released, you shall be able to upgrade without the need to change your code.

We will keep this issue open and inform you once the code with the fix are fully released.

**Comment by zhenlineo** [comment]
Note the error is `IllegalArgumentException` as it is considered as a misuse of the driver method. Hope it makes sense to you.

**Comment by nmervaillie** [comment]
Hi. Thanks for the update.
I'm totally fine with `IllegalArgumentException`

**Comment by lutovich** [comment]
Hi @nmervaillie,

Driver 1.7.0 containing the mentioned fix is now released.
I'll close this issue now. Please, feel free to update it if needed.
