### ISSUE TITLE
How to increase lock timeout?

### ISSUE THREAD

**Issue by kant111** [neo4j/neo4j-java-driver#610]
``
org.neo4j.driver.v1.exceptions.TransientException: LockClient[128] can't wait on resource RWLock[NODE(2246321), hash=1800573972] since => LockClient[128] <-[:HELD_BY]- RWLock[NODE(2248644), hash=1705462156] <-[:WAITING_FOR]- LockClient[127] <-[:HELD_BY]- RWLock[NODE(2246321), hash=1800573972]
``

I am getting the above exception not quite sure why? and I wonder why a user needs to worry about this? Is there a way to increase the lock time out?

**Comment by zhenlineo** [comment]
Hi,
Thanks very much for your question, you can increate lock timeout on the server side in the config file with [`dbms.lock.acquisition.timeout`](https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.lock.acquisition.timeout).

You get this exception probably because you have multiple transactions trying to access the same resources (in the above case NODE(2246321), hash=1800573972) at the same time. This lock timeout prevent from deadlocks in the database. You can read more about transactions and locks [here](https://neo4j.com/developer/kb/understanding-transaction-and-lock-timeouts/).

Finally, you can also make the driver to retry your transactions when this happens by using TransactionFunctions, a.k.a.`Session#readTransaction` and `Session#writeTransaction` methods, you can also read more [here](https://neo4j.com/docs/driver-manual/1.7/sessions-transactions/#driver-transactions-transaction-functions).

Also I would like to mention that Issues are mainly used for bug report and/or feature request. If you have more questions about how to use drivers and/or neo4j, please use [Neo4j Online Community](https://community.neo4j.com/) or other means mentioned in issue template.

Regards,
Zhen
