### ISSUE TITLE
can't access statement result in 4.0.0-beta03

### ISSUE THREAD

**Issue by sim732** [neo4j/neo4j-java-driver#647]
Hi,

When running 
val sr: StatementResult = session.readTransaction(tx => tx.run(q, ps))
sr.hasNext()
i got 
2019-11-13 12:43:12,041 [error] [application-akka.actor.default-dispatcher-2] c.LoginController - Cannot access records on this result any more as the result has already been consumed or the statement runner where the result is created has already been closed.
but above works well with 1.7.5 
Any idea?

**Comment by zhenlineo** [comment]
Hi @sim732,

You cannot pass a `StatementResult` back from a transaction function, as the transaction function commit the transaction internally at the end of the execution before it returns the result back.

Once a transaction is committed, all resources including the result will be released.

The correct way of using this API is to work on the result inside your read transaction, or return all records in a list such as 
`session.readTransaction(tx => tx.run(q, ps).toList());`

Cheers,
Zhen

**Comment by sim732** [comment]
Hi Zhen,

Thank you for a comprehensive reply.
To use a result inside transaction is not a good idea, because in case of long running operation
we have to keep  session open for a long time.
Your way of using API such as  session.readTransaction(tx => tx.run(q, ps).list())  really works,
but why not just return StatementResult(instead of records list) as it was in 1.7.5 driver ?

**Comment by zhenlineo** [comment]
Hi @sim732,

Your code is kind of equivalent to:
```
Transaction tx = session.beginTransaction();
StatementResult result = tx.run(q,ps);
tx.commit();
return result;
```
The transaction starts at the `begin` and ends at the `commit`. Once the transaction is committed, the resources (such as the connection with the server) are released.
 

In 1.7 anything unconsumed are all pulled and buffered, thus how you could get the result outside of the tx scope. With 4.0, we allow driver users to fully control the pulling pace. So if you think you do not need the result anymore, you can just discard the results without pulling all from server with `tx.commit`. If you still need the records, then you shall buffer all records into memory explicitly with `result.list()`. 

In our old 1.7 docs we've already not recommending to pulling tx resources out of transaction scope: "Any query results obtained within a transaction function should be consumed within that function. Transaction functions can return values but these should be derived values rather than raw results." You can read more in https://neo4j.com/docs/driver-manual/current/sessions-transactions/#driver-transactions-transaction-functions

Cheers,
Zhen

**Comment by sim732** [comment]
Hi Zhen,

Thank you for the explanation
