### ISSUE TITLE
Provide the used PGP public keys on your site

### ISSUE THREAD

**Issue by FSchumacher** [neo4j/neo4j-java-driver#794]
I want to check the released maven artefacts of org.neo4j:neo4j:4.2.0 against a published pgp key known to be in possesion of neo4j.

At the Apache JMeter project we started to verify all maven artefacts -- if possible -- by their PGP signatures. The key used for signing the neo4j artefacts has changed since at least 4.0.1 version (which was `0x7ad289796be2ffe2`) to `0xf8052e4e1bd0db31`. That key seems to belong to `identity@neo4j.com` (looked it up by using some of the various PGP keyservers), but it would be nice, if the used (public) keys would be published prominently on the neo4j websites or even in the source repo itself.

**Neo4j Version:** 4.2.0 Community  
**Neo4j Mode**: irrelevant  
**Driver version**: Java driver coming with the 4.2.0 jars
**Operating System:** irrelevant

### Steps to reproduce
1. Start a search for `f8052e4e1bd0db31` on your favourite search machine
### Expected behavior
Find the pgp public key on some site that clearly belongs to neo4j (project or product)
### Actual behavior
No results found.

**Comment by gjmwoods** [comment]
Hi @FSchumacher. Many thanks for pointing this out. We'll look into publishing the public keys, most likely on our website (the same key is shared with neo4j server itself).

As an aside, I believe that Maven central requires some proof that we are in possession of the domain so that should add to the confidence that we are in fact the publishers.

**Comment by gjmwoods** [comment]
Hi @FSchumacher. The PGP key has finally been published on our website at: https://neo4j.com/download-center/#pgp-key. Many thanks!
