### ISSUE TITLE
Slow 1st Request

### ISSUE THREAD

**Issue by magaton** [neo4j/neo4j-java-driver#885]
## Guidelines

- Neo4j version: Community 4.2.4
- Neo4j Mode: Single instance
- Driver version: java driver 4.2.4 through neo4j-java-driver-spring-boot-starter 4.2.4.0
- Operating system: Mac Osx, Big Sur, JDK 11

## Example bug report
Explained in details here:
https://github.com/neo4j-graphql/neo4j-graphql-java/issues/213#issuecomment-827112466

### Steps to reproduce
1. Start Neo4j locally
2. Run https://github.com/neo4j-graphql/neo4j-graphql-java/examples/graphql-spring-boot app
3. Execute graphql query, e.g {team { id} } from http://localhost:8080/playground. This one takes couple of seconds
4. Run another query, e.g {player { id} } from http://localhost:8080/playground. This one completes instantly

### Expected behavior
The first and subsequent requests should not have such a different execution time. DB is warmed up.

**Comment by injectives** [comment]
Thanks for reaching out. 👍 

As this issue was created on the driver project, it would be best to exclude software that is built on top of the driver from reproduction steps in order to check how driver performs on its own.

It would also be worth mentioning that this driver manages and uses a set connection pools and may maintain a routing state, meaning that it also benefits from a warm up. It is not just about warming up the server(s). A significant reason for fast subsequent query executions is the work that is done in the first execution, which takes longer.

Updated reproduction steps:
1. Start Neo4j on local container environment using the following image `neo4j:4.3.1`.
2. Create a small application that runs the same query N times.
3. Run the application to warm up the server.
4. Run the application one more time and measure the execution times.

The following pseudocode shows a simple application:
```
try ( Driver driver = GraphDatabase.driver( "neo4j://localhost:7687", AuthTokens.basic( "neo4j", "secret" )) )
{
    for ( int i = 0; i < 10; i++ )
    {
        {
            try ( Session session = driver.session() )
            {
                long startTime = System.nanoTime();
                session.run( "UNWIND range(0, 15) AS x RETURN x" ).list();
                long endTime = System.nanoTime();
            }
        }
    }
}
```

Timings:
1. 350ms
2. 16ms
3. 16ms
4. 10ms
5. 14ms
6. 36ms
7. 21ms
8. 11ms
9. 11ms
10. 30ms

As can be seen, the first execution took 350ms while the subsequent executions took 18.3ms on average.

First execution timeline:
- 24ms - Initial bootstrapping and internal logic execution.
- 7ms - Netty-based pool creation for routing.
- 1ms - Internal logic execution.
- 230ms - Netty channel acquisition for routing that necessitates a new channel creation and further bootstrap.
- 5ms - Internal logic execution.
- 20ms - Routing table update.
- 1ms - Netty-based pool creation for querying.
- 1ms - Internal logic execution.
- 23ms - Netty channel acquisition for querying that necessitates a new channel creation.
- 10ms - Internal logic execution.
- 28ms - Query and internal logic execution.

Second execution timeline:
- 1ms - Internal logic execution.
- 2ms - Netty channel acquisition for querying that just borrows the previously created channel from the pool.
- 1ms - Internal logic execution.
- 12ms - Query and internal logic execution.

As demonstrated, the second execution has a lot less steps and benefits from the work completed in first execution.

Aside from the general overhead of loading/bootstrapping everything, the first execution involves:
- Setting up routing that took 263ms in total:
  - 7ms (454 - 461) - Netty-based pool creation for routing.
  - 1ms (461 - 462) - Internal logic execution.
  - 230ms (462 - 692) - Netty channel acquisition for routing that necessitates a new channel creation and further bootstrap.
  - 5ms (692 - 697) - Internal logic execution.
  - 20ms (697 - 717) - Routing table update.
- Setting up connectivity for querying that took 24ms in total:
  - 1ms (717 - 718) - Netty-based pool creation for querying.
  - 23ms (719 - 742) - Netty channel acquisition for querying that necessitates a new channel creation.

These additional responsibilities alone took 287ms in total that is about 81% of total execution time, but are fundamental for fast subsequent executions.

I hope this provides a good explanation of the difference in execution times. It does not look like there is a problem with the driver itself. If additional projects are used that are based on the driver, it may be worth checking their execution times and raising an issue in the relevant project as the relevant maintainers may be able to provide more clarity on their behaviour.

**Comment by magaton** [comment]
Thanks for such a detailed response. 
If the driver does only what is needed in the 1st request, why one cannot experience the same problem in neo4j js driver.
I am running the same graphql schema in spring-boot with neo4j java driver and grandstack with neo4j js driver (via neo4j-graphql-js) and only in java version i hit the slow 1st request.
Can't you do warmup in the app start time from the driver itself or in other words, how is js driver different so this issue is not present?

**Comment by injectives** [comment]
There is no expectation that all drivers have to match in terms of performance. In the end of the day, they are different implementations in different languages with potentially different dependencies.
For instance, the current implementation of the Java Driver uses a client server framework that takes some time to load. Furthermore, networking implementation is potentially more complex, meaning that the driver may take longer to setup new connection pools and new connections in them. However, once this happens the performance is quite good.

For instance, below are the results with the other driver:
1. 44
2. 46
3. 46
4. 47
5. 47
6. 48
7. 49
8. 48
9. 52
10. 49

And here are the results with compiled java app with logging turned off (to match the other driver):
1. 229
2. 7
3. 6
4. 7
5. 7
6. 7
7. 7
8. 6
9. 6
10. 8

While the first execution does take longer, the driver has good performance afterwards. At present, we do not have evidence that ahead of time and potentially continuous communication with server(s) would be preferable. Routing tables have TTL that may well expire before application decides to run something and cluster composition may change as well.

Having said that, there is nothing stopping users from invoking `driver.verifyConnectivity()` method that triggers network communication and bootstraps the driver further. In case of a single node setup, running a basic query (like `RETURN 0`) is also an option.

Results after invoking `driver.verifyConnectivity()`:
1. 46
2. 6
3. 5
4. 6
5. 6
6. 5
7. 5
8. 6
9. 5
10. 7

Results after running a basic query on single node setup:
1. 7
2. 7
3. 8
4. 6
5. 6
6. 5
7. 6
8. 5
9. 5
10. 6

**Comment by bigmontz** [comment]
The Javascript driver also does some bootstrap during the first user interaction with the server (by verifyConnectivity, creating session and run a query, etc). It fetch routing information when needed, creates the connection pool and creates the connection which will be used for running the query. This connection is released back to the pool after the work is done to be reused in the subsequents queries. 

The biggest difference is in the way the pool is managed. JS uses [its own pool implementation](https://github.com/neo4j/neo4j-javascript-driver/blob/4.3/bolt-connection/src/pool/pool.js) which makes its bootstrap  lighter than the Java driver bootstrap.

**Comment by injectives** [comment]
At present, it looks like the driver works as expected given the current design and implementation. Users can call the `verifyConnectivity()` method in order to get networking bootstrapped further and check if they have connectivity in place. While being more complex, this implementation also provides some nice features, like implementing a look ahead cursor when fetching results.
There are some ideas about having a pool-free version of drivers as it may be useful in certain cases. We will need to see if there is a sufficient interest in this.
